name: flutter_screenutil_safearea
description: A custom version of flutter_screenutil for adapting screen and font size with safe area consideration.
version: 0.0.2
homepage: https://github.com/neatbee/flutter_screenutil_safearea

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
